# Generated by Django 2.2.2 on 2019-07-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('zip', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=32)),
                ('name_last', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrc_Id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=32)),
                ('thc_level', models.DecimalField(decimal_places=4, max_digits=4)),
                ('cbd_level', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Person')),
                ('hire_date', models.DateField()),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('main.person',),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateField()),
                ('date_harvested', models.DateField()),
                ('weight_harvested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tag', models.CharField(max_length=32)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Strain')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('facility_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Facility')),
                ('plants', models.ManyToManyField(blank=True, to='main.Plant')),
            ],
            bases=('main.facility',),
        ),
    ]
