# Generated by Django 2.2.2 on 2019-07-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_name',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
